name: storage_fly
description: Local web storage key value written in Dart and strongly encrypted to use in Flutter Web, based on indexed_db.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.4.0-dev <3.0.0'